// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace sakila.Models
{
    public partial class FilmText
    {
        public short FilmId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    }
}